oneComhw3
AndreaDiaz23/goit-nodejs-hw-restapi pull request #2
Opened 2024-05-08 03:03 UTC by AndreaDiaz23

Hola profe te envio tarea 3

2024-05-08 06:35 UTC, Alonaklzh requested changes
hola, no puedo encontrar contacto por id https://gyazo.com/37307d3b896accc48205c667ca550a34

2024-05-08 23:01 UTC, AndreaDiaz23 commented
listo profe!!

2024-05-09 06:24 UTC, Alonaklzh requested changes
hola
ahora no funciona put, dice lo mismo, id no encontrado, y no veo la ruta patch

2024-05-09 23:10 UTC, AndreaDiaz23 commented
profe ya puse el patch y creo que ya pude hacer put con un contacto, me puedes confirmar si ahora si quedo bien? Un abrazo, gracias por la paciencia

2024-05-10 20:24 UTC, Alonaklzh approved these changes
genial, gracias

2024-05-10 20:24 UTC, merged